name: AutoNicho AutoDiscover (Pages)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"   # diario 06:00 UTC (~08:00 España)

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install jinja2 requests

      - name: Write BOOTSTRAP_JSON to file (safe)
        env:
          RAW: ${{ secrets.BOOTSTRAP_JSON }}
        run: |
          mkdir -p automation
          python - <<'PY'
          import os, pathlib
          raw = os.environ.get('RAW','')
          p = pathlib.Path('automation/bootstrap.json')
          p.write_text(raw, encoding='utf-8')
          print('Wrote', p, 'len=', len(raw))
          PY

      - name: Generate site (AutoDiscover)
        env:
          BOOTSTRAP_JSON_PATH: automation/bootstrap.json
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          python automation/generate_autodiscover.py

      - name: Upload artifact (public/)
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
